#line 2 "T:\\stuff\\flex\\luacompiler\\/lex.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
static yyconst short int yy_accept[196] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   95,   94,   91,   12,   59,   57,   60,   13,
       73,   74,   55,   53,   81,   54,   82,   56,   86,   86,
       80,   52,   70,   72,   71,   92,   92,   89,   77,   78,
       58,   92,   92,   92,   89,   92,   92,   92,   92,   92,
       92,   92,   92,   91,   92,   92,   92,   75,   62,   76,
       61,    3,    2,    5,    7,   15,   28,   94,   14,   27,
        9,   94,    0,    1,   83,   89,   65,   89,   86,   93,
       89,   93,   79,   63,   68,   66,   69,   64,   92,   89,
        0,    8,   92,   92,   37,   92,   92,   92,   92,   92,

       92,   46,   49,   92,   92,   92,   43,   92,   92,   92,
       92,   92,   92,   67,    6,   15,   24,   16,   26,   17,
       18,   19,   23,   20,   21,   22,   25,   14,    9,   10,
        0,   11,    0,   84,   87,    0,   89,   88,   89,   85,
       29,   92,   92,   48,   92,   34,   92,   92,   92,   35,
       39,   92,   92,   92,   92,   92,   92,   92,   25,    0,
       89,   90,   88,   92,   41,   92,   92,   42,   92,   92,
       92,   92,   32,   36,   92,   92,    4,   88,   33,   92,
       30,   92,   31,   51,   92,   92,   40,   44,   45,   92,
       47,   50,   92,   38,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   25,   25,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   30,   31,   27,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   27,   41,   42,   27,   43,
       44,   45,   27,   46,   47,   48,   49,   50,   51,   52,
       27,   53,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    4,    5,    1,    4,    4,    1,    1,
        1,    1,    1,    4,    4,    4,    4,    1,    6,    7,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[207] =
    {   0,
        0,    0,  454,  453,  424,  423,   50,   51,   56,   57,
      422,  421,  450,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,   48,   53,   73,   78,
       54,  422,   50,   56,   75,  421,  420,   93,   98,  419,
      418,   62,   67,   80,   40,   86,   87,  101,   88,  102,
      103,  107,   92,  417,  108,  109,  119,  416,  415,  414,
      123,  457,  457,  457,  397,    0,  457,  157,    0,  457,
        0,  118,  412,  457,  145,  149,  457,  161,  411,  136,
      178,  201,  457,  457,  457,  457,  457,  457,  410,  409,
      146,  457,  120,  155,  394,   89,  142,  156,  127,  129,

      169,  390,  387,  168,  166,  172,  384,  192,  195,  185,
      174,  197,  199,  457,  457,    0,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  226,    0,    0,  457,
      200,  457,  328,  229,  233,  245,  249,  341,  235,    0,
      340,  125,  240,  338,  210,  336,  227,  187,  242,  335,
      334,  244,  254,  228,  256,  258,  264,  170,  277,  319,
      274,  280,  294,  272,  268,  269,  259,  332,  279,  270,
      282,  287,  331,  328,  289,  288,  457,  308,  327,  301,
      326,  303,  325,  323,  305,  308,  322,  321,  318,  313,
      314,  113,  315,   63,  457,  358,  365,  372,  379,  386,

      390,   71,  395,  402,  409,  415
    } ;

static yyconst short int yy_def[207] =
    {   0,
      195,    1,  196,  196,  197,  197,  198,  198,  199,  199,
      200,  200,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  201,  201,
      195,  195,  195,  195,  195,  202,  202,  202,  195,  195,
      195,  202,  202,  202,   38,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  195,  195,  195,
      195,  195,  195,  195,  195,  203,  195,  195,  204,  195,
      205,  206,  195,  195,  195,  195,  195,  195,   30,  201,
      201,  201,  195,  195,  195,  195,  195,  195,  202,   38,
      195,  195,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  195,  195,  203,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  204,  205,  195,
      195,  195,  195,  195,  195,  195,  195,   81,   81,   82,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  195,  195,
      195,  195,  195,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  195,  195,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,    0,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195
    } ;

static yyconst short int yy_nxt[515] =
    {   0,
       14,   15,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   37,   39,   14,   40,
       41,   42,   43,   37,   44,   45,   46,   47,   37,   48,
       37,   49,   50,   51,   52,   53,   54,   55,   56,   37,
       57,   37,   37,   58,   59,   60,   61,   67,   67,   70,
       70,   73,   75,   73,   76,   76,   73,   73,   77,   73,
       84,   85,   83,   76,   89,   73,  195,   86,   68,   68,
       73,   96,   97,   76,   68,   68,   73,   78,   73,   79,
       79,   73,   78,   73,   79,   79,   87,   88,   81,   73,

       73,   73,  195,   81,   93,   73,   73,   76,   81,   90,
       90,   73,   94,   81,   73,   73,   73,   98,   90,   91,
       73,   73,   73,   95,   82,   92,  195,  109,   90,   99,
      101,  104,   73,  195,  100,  143,   73,  102,  195,  131,
      195,  105,  195,  103,  114,  106,  110,  132,  107,  195,
      195,  112,  108,  111,  141,  195,  164,  113,  117,  134,
      118,   76,   76,   76,  119,   76,   76,   91,  195,  195,
       76,  147,  146,   92,   76,   76,  144,  135,  135,  195,
       76,  195,  195,  195,   76,  195,   76,  195,  120,  121,
      142,  136,  137,  122,  138,  138,   76,  145,  195,  123,

      195,  149,  124,  139,  125,  195,  126,  150,  195,  127,
      195,  176,  195,  139,  195,  195,  148,  140,  140,  151,
      155,  131,  156,  195,  140,  140,  140,  159,  159,  132,
      168,  152,  140,  140,  140,  140,  140,  140,  158,  153,
      195,  195,  154,   76,  157,   76,   76,   76,  195,  135,
      135,  139,  139,  195,   76,  195,  166,  195,  161,  162,
      167,  163,  163,  137,   76,  137,  137,  195,  161,  195,
      162,  195,  195,  169,  137,  165,  172,  195,  159,  159,
      162,  195,  195,  195,  137,  195,  170,  136,  137,  171,
      178,  178,  195,  174,  162,  195,  162,  162,  173,  137,

      195,  195,  195,  175,  181,  162,  182,  180,  162,  137,
      163,  163,  179,  185,  195,  162,  195,  184,  195,  162,
      183,  195,  137,  188,  178,  178,  195,  195,  195,  162,
      187,  195,  186,  137,  195,  195,  195,  189,  195,  195,
      195,  195,  190,  137,  195,  195,  177,  195,  195,  195,
      192,  195,  191,  195,  195,  160,  193,  194,   62,   62,
       62,   62,   62,   62,   62,   64,   64,   64,   64,   64,
       64,   64,   66,   66,   66,   66,   66,   66,   66,   69,
       69,   69,   69,   69,   69,   69,   71,   71,   71,   71,
       71,   71,   71,   80,   80,  116,  116,  195,  116,  116,

      195,  116,  128,  195,  128,  128,  128,  195,  128,  129,
      129,  129,  129,  129,  129,  130,  130,  130,  130,  130,
      130,  130,  195,  195,  195,  133,  115,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   74,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,  195,
       72,   72,   65,   65,   63,   63,   13,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195
    } ;

static yyconst short int yy_chk[515] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    8,    9,
       10,   27,   27,   33,   27,   27,   28,   31,   28,   34,
       33,   33,   31,   27,  202,   42,  194,   34,    7,    8,
       43,   45,   45,   27,    9,   10,   29,   29,   35,   29,
       29,   30,   30,   44,   30,   30,   35,   35,   29,   46,

       47,   49,   96,   30,   42,   53,   38,   38,   29,   38,
       38,   39,   43,   30,   48,   50,   51,   46,   38,   39,
       52,   55,   56,   44,   29,   39,  192,   53,   38,   46,
       47,   49,   57,   93,   46,   96,   61,   48,  142,   72,
       99,   50,  100,   48,   61,   50,   55,   72,   51,   80,
       80,   56,   52,   55,   93,   97,  142,   57,   68,   75,
       68,   75,   75,   76,   68,   76,   76,   91,   94,   98,
       75,  100,   99,   91,   76,   78,   97,   78,   78,  105,
       75,  104,  101,  158,   76,  106,   78,  111,   68,   68,
       94,   81,   81,   68,   81,   81,   78,   98,  110,   68,

      148,  104,   68,   81,   68,  108,   68,  105,  109,   68,
      112,  158,  113,   81,   82,   82,  101,   82,   82,  106,
      110,  131,  111,  145,   82,   82,   82,  127,  127,  131,
      148,  108,   82,   82,   82,   82,   82,   82,  113,  109,
      147,  154,  109,  134,  112,  134,  134,  135,  139,  135,
      135,  139,  139,  143,  134,  149,  145,  152,  135,  136,
      147,  136,  136,  137,  134,  137,  137,  153,  135,  155,
      136,  156,  167,  149,  137,  143,  154,  157,  159,  159,
      136,  165,  166,  170,  137,  164,  152,  161,  161,  153,
      161,  161,  169,  156,  162,  171,  162,  162,  155,  161,

      172,  176,  175,  157,  166,  162,  167,  165,  163,  161,
      163,  163,  164,  171,  180,  162,  182,  170,  185,  163,
      169,  186,  178,  176,  178,  178,  190,  191,  193,  163,
      175,  189,  172,  178,  188,  187,  184,  180,  183,  181,
      179,  174,  182,  178,  173,  168,  160,  151,  150,  146,
      186,  144,  185,  141,  138,  133,  190,  193,  196,  196,
      196,  196,  196,  196,  196,  197,  197,  197,  197,  197,
      197,  197,  198,  198,  198,  198,  198,  198,  198,  199,
      199,  199,  199,  199,  199,  199,  200,  200,  200,  200,
      200,  200,  200,  201,  201,  203,  203,  107,  203,  203,

      103,  203,  204,  102,  204,  204,  204,   95,  204,  205,
      205,  205,  205,  205,  205,  206,  206,  206,  206,  206,
      206,  206,   90,   89,   79,   73,   65,   60,   59,   58,
       54,   41,   40,   37,   36,   32,   26,   25,   24,   23,
       22,   21,   20,   19,   18,   17,   16,   15,   14,   13,
       12,   11,    6,    5,    4,    3,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "T:\\stuff\\flex\\luacompiler\\/code.l"
#define INITIAL 0
/*** Definition Section ***/
#define YY_NEVER_INTERACTIVE 1
#line 6 "T:\\stuff\\flex\\luacompiler\\/code.l"
    #include <string.h>
    #include <math.h>
    #include <stdlib.h>
    char str[1000];
    int stringOpenerLevel = 0;
    long long iNumber = 0;
    double fNumber;
/*** Rule Section ***/
#define SINGLE_LINE_COMMENT 1

#define MULTILINE_COMMENT 2

#define SINGLE_QUOTE_STRING 3

#define DOUBLE_QUOTE_STRING 4

#define LONG_BRACKET_STRING 5

#line 570 "T:\\stuff\\flex\\luacompiler\\/lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 21 "T:\\stuff\\flex\\luacompiler\\/code.l"

#line 723 "T:\\stuff\\flex\\luacompiler\\/lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 196 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 457 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Found single-line comment\n"); BEGIN(SINGLE_LINE_COMMENT);};
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 "T:\\stuff\\flex\\luacompiler\\/code.l"
{BEGIN(INITIAL);};
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "T:\\stuff\\flex\\luacompiler\\/code.l"
{};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Found multiline comment\n"); BEGIN(MULTILINE_COMMENT);};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "T:\\stuff\\flex\\luacompiler\\/code.l"
{};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Ended multiline comment\n"); BEGIN(INITIAL);};
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "T:\\stuff\\flex\\luacompiler\\/code.l"
{};
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcpy(str, ""); stringOpenerLevel = yyleng; BEGIN(LONG_BRACKET_STRING);};
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 32 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, yytext);};
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 33 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, yytext);};
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 34 "T:\\stuff\\flex\\luacompiler\\/code.l"
{
    if(stringOpenerLevel == yyleng)
    {
        printf("String literal: %s\n", str);
        BEGIN(INITIAL);
    }
    else
        strcat(str, yytext);
};
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcpy(str, ""); BEGIN(DOUBLE_QUOTE_STRING);};
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcpy(str, ""); BEGIN(SINGLE_QUOTE_STRING);};
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, yytext);};
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, yytext);};
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, "\"");};
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 49 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, "\a");};
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 50 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, "\b");};
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 51 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, "\f");};
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 52 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, "\r");};
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 53 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, "\t");};
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 54 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, "\v");};
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 55 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, "\n");};
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 56 "T:\\stuff\\flex\\luacompiler\\/code.l"
{};
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 57 "T:\\stuff\\flex\\luacompiler\\/code.l"
{};
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 58 "T:\\stuff\\flex\\luacompiler\\/code.l"
{strcat(str, "'");};
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 59 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("String literal: %s\n", str); BEGIN(INITIAL);};
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 60 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("String literal: %s\n", str); BEGIN(INITIAL);};
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 78 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Keyword: %s\n", yytext);};
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Print call: %s\n", yytext);};
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Empty statement: %s\n", yytext);};
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 90 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 91 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 92 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 93 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 94 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 95 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 96 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 97 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 98 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 99 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 100 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 101 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 102 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 103 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 104 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 105 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 106 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 107 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 108 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 109 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 110 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 111 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 112 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 113 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 114 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 115 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 116 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 117 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Operator: %s\n", yytext);};
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 118 "T:\\stuff\\flex\\luacompiler\\/code.l"
{iNumber = strtol(yytext, NULL, 16); printf("Integral number: %d\n", iNumber);};
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 119 "T:\\stuff\\flex\\luacompiler\\/code.l"
{iNumber = atoi(yytext); printf("Integral number: %d\n", iNumber);};
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 120 "T:\\stuff\\flex\\luacompiler\\/code.l"
{
    fNumber = atof(yytext);
    printf("Floating-point number: %f\n", fNumber);
    };
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 124 "T:\\stuff\\flex\\luacompiler\\/code.l"
{
    int sign = 1;
    char *eEntry = strchr(yytext, 'e');
    if (eEntry == NULL)
        eEntry = strchr(yytext, 'E');
    char p1[100];
    char p2[100];
    strncpy(p1, yytext, (eEntry - yytext));
    p1[(eEntry - yytext)] = '\0';
    char *p2ptr = eEntry + 1;
    if (*p2ptr == '-')
    {
        sign = -1;
        p2ptr += 1;
    }
    strcpy(p2, p2ptr);
    double f1 = atof(p1);
    int f2 = atoi(p2);

    fNumber = f1 * pow(10, f2 * sign);
    printf("Floating-point number: %f\n", fNumber);
};
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 146 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Impossible number literal: %s\n", yytext);};
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 147 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Impossible number literal: %s\n", yytext);};
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 148 "T:\\stuff\\flex\\luacompiler\\/code.l"
{}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 149 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Identifier: %s\n", yytext);};
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 150 "T:\\stuff\\flex\\luacompiler\\/code.l"
{printf("Impossible token: %s\n", yytext);};
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 151 "T:\\stuff\\flex\\luacompiler\\/code.l"
ECHO;
	YY_BREAK
#line 1308 "T:\\stuff\\flex\\luacompiler\\/lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLE_LINE_COMMENT):
case YY_STATE_EOF(MULTILINE_COMMENT):
case YY_STATE_EOF(SINGLE_QUOTE_STRING):
case YY_STATE_EOF(DOUBLE_QUOTE_STRING):
case YY_STATE_EOF(LONG_BRACKET_STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 196 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 196 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 195);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 151 "T:\\stuff\\flex\\luacompiler\\/code.l"

 
/*** Code Section ***/
int main() {
 
FILE *fp;
char filename[50];
printf("Enter the filename: \n");
scanf("%s",filename);
fp = fopen(filename,"r");
yyin = fp;
 
yylex();
 
return 0;
}
